### ISSUE TITLE
better design

### ISSUE THREAD

**Issue by Mustwey** [lewisgibson/monopoly-go-bot#13]
why not just find the buttons in memory and design it like that?

use cheat engine and ui automator for this

**Comment by lewisgibson** [comment]
I appreciate your suggestion @Mustwey, but I've chosen a different approach for this project. Using memory and UI manipulation tools can be effective, but I want to keep this project accessible to a wide audience, respect the game's terms, and provide opportunities for Python developers to actively contribute.

Feel free to share any other ideas or feedback. This project is open to collaboration and improvements.
