### ISSUE TITLE
buttons not found

### ISSUE THREAD

**Issue by DrEffect** [lewisgibson/monopoly-go-bot#7]
the bot doesnt find the right buttons, oftern it didnt found any button and if it find a button on the completly wron position, maybe  some settings error on my site?

**Comment by Krazalm** [comment]
I just fixed mine by replacing new images. U can also put any img and it will click them

**Comment by DrEffect** [comment]
maybe you can upload Your  Fixed images anywhere?:-)

**Comment by Krazalm** [comment]
I dont think it will work due to my computer color tone I recommend to do it in ur pc manually

**Comment by DrEffect** [comment]
just take a screenshot of it?  Any special recommendations for the
Screenshot? hopefully i will get it work....
somethin else where i have a look on it? cause its detected, completely the
whole buttons


Am Mo., 7. Aug. 2023 um 13:36 Uhr schrieb Krazalm ***@***.***

**Comment by Krazalm** [comment]
![jail-roll](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/78bc0761-8bc5-4f17-859b-ec175c95b7b5)
![megaheist](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/65d9df5f-4874-4b86-91ef-e70ab4ecd61b)
![quick-wins-tap-to-claim](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/3bc38c23-1eb7-49d3-8540-9ecf3e6e94e1)
![shutdown-marker](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/d29b4883-9319-4663-bb60-5c6a7cd85f43)
![skip](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/22ebf83f-52e9-4554-8be5-b1012ed8e650)
![taptoclaim](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/949fde7c-bed2-43b2-ac62-3780288e0114)
![upgrade](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/40b28e5e-dc3b-473e-a109-4c77368d1847)
![zz__quick-wins-exit](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/f39c453b-a25f-420c-ab8f-5dc8c9fa3725)
![advertisement-close](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/9c756634-f335-40dd-9232-e18b40be6e8e)
![bank-heist-door](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/3a7535ff-a056-433f-aa93-c0622ff47422)
![build](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/f88126c5-a0fb-4c77-9122-6aa495190ace)
![cancel](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/bba3c398-27cb-4e17-918c-4033dc431fa3)
![Capture](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/d5e0ad7c-24b7-4930-bef2-409e014df0b1)
![Capture2](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/418aa818-dbe1-425e-8fa8-092026be4484)
![community-chest-collect](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/cd21862d-fec7-41bc-bfc9-51e5fe48f134)
![community-chest-start](https://github.com/lewisgibson/monopoly-go-bot/assets/84464398/31896181-aa5b-4fe5-a923-8ac04cdeb8c7)

**Comment by lewisgibson** [comment]
Although we do image detection in black and white (xor comparison) there are still some issues with slight variations of grey. The solution is to probably make the searching a little more aggressive.

**Comment by lewisgibson** [comment]
You can change the confidence parameter here if you wish to do that: https://github.com/lewisgibson/monopoly-go-bot/blob/main/main.py#L56

**Comment by DrEffect** [comment]
higher is more aggresiv i think?

**Comment by lewisgibson** [comment]
> higher is more aggresiv i think?

It's the other way around. A value of 1.00 (100%) means the screen capture and the target image need to be 100% identical. A value of 0.75 (75%) means they need 75% similarity.

The comparison is done using OpenCV's `matchTemplate` call in `TM_CCOEFF_NORMED` mode.

https://stackoverflow.com/a/55469775
https://docs.opencv.org/4.0.1/df/dfb/group__imgproc__object.html#ga3a7850640f1fe1f58fe91a2d7583695d

**Comment by Krazalm** [comment]
I added customizable keybind in the code and many other stuff check it out Xd
`import sys
import time
import pyautogui
import glob
import pyscreeze
import PIL.Image
import pynput
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

class Monopoly:
    def __init__(self, delay: float, confidence: float, toggle_key) -> None:
        self.delay = delay
        self.confidence = confidence
        self.images_path = "images"
        self.toggle_key = toggle_key
        self.cache = {}

        self.running = False
        self.keyboard_listener = pynput.keyboard.Listener(on_press=self.on_key_press)
        self.keyboard_listener.start()

        self.print_banner()

        while True:
            if self.running:
                self.process_images()
            time.sleep(self.delay)

    def print_banner(self) -> None:
        print("Monopoly Go! Bot")
        print(f"\nPress {self.toggle_key} to toggle running.\n")

    def on_key_press(self, key) -> None:
        if key.char == self.toggle_key:
            self.toggle_running()

    def toggle_running(self) -> None:
        self.running = not self.running
        status = "Started" if self.running else "Stopped"
        print(f"{status}\n")

    def process_images(self) -> None:
        for path in self.get_sorted_images():
            if not self.running:
                break
            if self.process_image(path):
                break

    def get_sorted_images(self) -> list:
        return sorted(glob.glob(f"{self.images_path}/*.png"))

    def load_image(self, path: str) -> PIL.Image.Image:
        if path not in self.cache:
            self.cache[path] = PIL.Image.open(path)
        return self.cache[path]

    def find(self, image: PIL.Image.Image) -> pyscreeze.Point | None:
        result = pyautogui.locateOnScreen(image, grayscale=True, confidence=self.confidence)
        return pyautogui.center(result) if result else None

    def process_image(self, path: str) -> bool:
        image = self.load_image(path)
        point = self.find(image)

        if point:
            print(f"Scanning for {path} -> ({point.x}, {point.y})")
            pyautogui.moveTo(x=point.x, y=point.y, duration=0.2)
            pyautogui.click()
            return True

        print(f"Scanning for {path}")
        return False

try:
    toggle_key = input("Enter a key to use as toggle: ").lower()
    Monopoly(delay=0.1, confidence=0.75, toggle_key=toggle_key)
except KeyboardInterrupt:
    sys.exit()
`

**Comment by Krazalm** [comment]
Hey edited ur code

Optimized and Enhanced Code:

The code has been enhanced for improved readability and performance. Configurable settings have been organized for easier management. The code now relies on the pyautogui library for faster mouse input and has been optimized for efficiency. Logging has been introduced to track the code's execution.

Notable Changes:
- Replaced the usage of 'pyautogui.locateOnScreen' with 'pyautogui.locateCenterOnScreen' for precise mouse positioning.
- Removed dependencies on 'pydirectinput' and 'sys' for a cleaner codebase.


[main.py.txt](https://github.com/lewisgibson/monopoly-go-bot/files/12294106/main.py.txt)


> > higher is more aggresiv i think?
> 
> It's the other way around. A value of 1.00 (100%) means the screen capture and the target image need to be 100% identical. A value of 0.75 (75%) means they need 75% similarity.
> 
> The comparison is done using OpenCV's `matchTemplate` call in `TM_CCOEFF_NORMED` mode.
> 
> https://stackoverflow.com/a/55469775 https://docs.opencv.org/4.0.1/df/dfb/group__imgproc__object.html#ga3a7850640f1fe1f58fe91a2d7583695d

**Comment by Krazalm** [comment]
Will also do a priority list function although its 2 am for me im a do it tommorow i got whole day [😊](https://emojipedia.org/smiling-face-with-smiling-eyes/)

**Comment by DrEffect** [comment]
ok slowly it will work, but now when i build and doent have money, it always try to build, is there anywhere a routine to stop doing the Same?

**Comment by lewisgibson** [comment]
@DrEffect Building is experimental. Delete the images to remove build support.
